module.exports = function (context, req) {
    var execution_timestamp = (new Date()).toJSON();  // format: 2012-04-23T18:25:43.511Z
    
    var messages = [];

    var www_wp_service = "www";
    var www_wp_environment = "prod";
    var www_wp_domain = "www.wrdsb.ca";
    var www_sites = [
        'empty',
        'planning',
        'pic',
        'facilities',
        'kindergarten',
        'beforeafter',
        'careers',
        'esu',
        'wefi',
        'french',
        'board-meetings',
        'learning-services',
        'labourupdate',
        'bipsa',
        'safeschools',
        'innovative-change',
        'labour',
        'catc',
        'continuing-education',
        'alternative-education',
        'ctcc',
        'register'
    ];

    var staff_wp_service = "staff";
    var staff_wp_environment = "prod";
    var staff_wp_domain = "staff.wrdsb.ca";
    var staff_sites = [
        'summer-contact',
        'eguide',
        'communications',
        'ell',
        'hr',
        'g-suite',
        'resources',
        'procurement-services',
        'policyprocedure',
        'k212-finance',
        'wordpress',
        'bslt',
        'learning-services',
        'elementary-catc',
        'software-support',
        'its',
        'example-handbook',
        'abe',
        'ayr',
        'bdn',
        'bre',
        'brp',
        'ced',
        'cha',
        'chc',
        'cle',
        'cnw',
        'coh',
        'con',
        'cor',
        'dks',
        'edc',
        'secondary-staffing',
        'dpk',
        'fhl',
        'flo',
        'hes',
        'hig',
        'hil',
        'jdp',
        'german',
        'jfc',
        'kea',
        'lau',
        'lbp',
        'lex',
        'lin',
        'lkw',
        'lnh',
        'man',
        'mea',
        'mjp',
        'mrg',
        'pkw',
        'pre',
        'qsm',
        'rye',
        'sag',
        'she',
        'sil',
        'snd',
        'sta',
        'sud',
        'tri',
        'wcp',
        'wgd',
        'wpk',
        'wsh',
        'wsm',
        'secondary-guidance',
        'empty-site',
        'alp',
        'ark',
        'ave',
        'bci',
        'bgd',
        'blr',
        'cdc',
        'cnc',
        'cre',
        'crl',
        'ctr',
        'doo',
        'eci',
        'eds',
        'elg',
        'elz',
        'emp',
        'est',
        'esu',
        'fgl',
        'fhc',
        'fra',
        'gci',
        'gps',
        'grc',
        'gvc',
        'gvn',
        'how',
        'hrh',
        'jam',
        'jhs',
        'jma',
        'jst',
        'jwg',
        'kci',
        'ked',
        'lrw',
        'mcg',
        'mck',
        'mil',
        'mof',
        'nam',
        'ndd',
        'nlw',
        'phs',
        'pio',
        'pkm',
        'pru',
        'qel',
        'riv',
        'rmt',
        'roc',
        'sab',
        'shl',
        'smi',
        'srg',
        'sss',
        'stj',
        'stn',
        'stw',
        'sun',
        'tai',
        'tbr',
        'wci',
        'wel',
        'wlm',
        'wls',
        'wod',
        'wsv',
        'wtt',
        'moodle',
        'social-workers',
        'sls',
        'library',
        'casl',
        'software-development',
        'basecamp',
        'french-immersion',
        'twea',
        'core-french',
        'wordpress-team',
        'itservice-desk',
        'itservicedesk-analysts',
        'dts',
        'trillium',
        'bfs',
        'vis',
        'networking',
        'ontap',
        'badges',
        'networking-team',
        'hss',
        'wellness',
        'school-teams',
        'special-education',
        'its-team',
        'gro',
        'environmental-education',
        'continuing-education',
        'gnss',
        'chi',
        'facilities-team',
        'bfs-team',
        'planning-team',
        'hr-team',
        'elementary-staffing',
        'ntip',
        'branding',
        'smartphones',
        'phones',
        'gcp',
        'training-new',
        'extended-day',
        'airwatch',
        'learning-services-staging',
        'airwatch-team',
        'jme',
        'windows10',
        'admissions-enrolment',
        'privacy',
        'cellphones',
        'research',
        'digital-citizenship',
        'dsps',
        'kindergarten',
        'elementary-admin',
        'secondary-admin',
        'technological-education',
    ];

    www_sites.forEach(wp_site => {
        var message = {
            wp_service: www_wp_service,
            wp_environment: www_wp_environment,
            wp_domain: www_wp_domain,
            wp_site: wp_site
        };
        messages.push(JSON.stringify(message));
    });

    staff_sites.forEach(wp_site => {
        var message = {
            wp_service: staff_wp_service,
            wp_environment: staff_wp_environment,
            wp_domain: staff_wp_domain,
            wp_site: wp_site
        };
        messages.push(JSON.stringify(message));
    });

    context.bindings.lamsonWpPostsList = messages;
    context.log(messages);
    context.done(null, messages);
};
